config/routes.rb
Rails.application.routes.draw do
  get 'list/index'

  get 'member/index'

  get 'minicurso/index'

  get 'confirmation/index'

  get 'lista', to: "list#index", as: 'geral'

  resources :administrators
  get 'checkout/:id', to: 'checkout#create', as: 'checkout'

  get 'n/:id' => 'notifications#create'

  get 'registres/painel' => 'registres#painel'

  get 'member', to: 'member#index', as: 'index'

  resources :panelists
  resources :courses
  resources :contacts
  devise_for :users, :controllers  => {
             :registrations => 'users/registrations',
             :sessions => 'users/sessions'
           }
  resources :minhainscricaos
  resources :palestra_inscricaos
  resources :palestras
  root 'menu#index'

  get 'pay/:id/user' => "checkout#create"

  get 'confirma/:id', to: "confirmation#index", as: 'confirmation'

  get 'menu/index'

  get 'inscricoes/index'
  
  get 'contato/index'

  get 'parceiros/index'

  get 'programacao/index'

  get 'inscricoes/index'

  get 'artigos/index'
  
  get 'comite_cientifico/index'

  get 'comissao_organizadora/index'

  get 'apresentacao/index'

  match ':controller(/:action(/:id))', :via => [:get, :post]

end

app/models/administrator.rb
class Administrator < ActiveRecord::Base
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :name, presence: true
  validates :email, presence: true,format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i}
  validates :telephone, presence: true
  validates :obs, presence: true
end

app/models/course.rb
class Course < ActiveRecord::Base
	enum category: [:first_day, :second_day]

	validates :name, presence: true
	validates :description, presence: true

	has_many :registereds
	has_many :users,
		:through => :registereds

	def self.available dia
		cursos = Course.where( category: dia )
		confirmados = cursos.to_a.select {|c| c.registereds.where(pay: 1).count < 20 }
	end		
end

app/models/minhainscricao.rb
class Minhainscricao < ActiveRecord::Base
end

app/models/panelist.rb
class Panelist < ActiveRecord::Base
  enum status: [:confirmed, :unconfirmed]

  belongs_to :user

  validates :article, presence: true
end

app/models/registered.rb
class Registered < ActiveRecord::Base
	enum pay: [:unconfirmed, :confirmed]

	belongs_to :user
	belongs_to :course
end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:normal_user, :admin]
  enum status: [:não_confirmado, :confirmado]
  
  #relactions
  has_many :registereds
  has_many :courses,
    :through => :registereds

  has_one :panelist

  validates :name, presence: true
  validates :cpf, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :telephone, presence: true
  validates :institution, presence: true
  validates :birthday, presence: true

  accepts_nested_attributes_for :registereds
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/minhainscricaos_controller.rb
class MinhainscricaosController < ApplicationController

  def index
    @inscricao = Inscricao.find(params[:id])
    @minicurso = Minicurso.all
    @palestra = Palestra.all
    render 'index'
  end

  def adicionar_minicurso
    minicurso = Minicurso.find(params[:id])
    @inscricao = Inscricao.find(params[:Inscricao])
    if minicurso.vagas>=1 && minicurso != nil
      minicurso.vagas -= 1
      minicurso.save
      Minicurso_inscricao.create(minicurso:minicurso, inscricao: @inscricao, data: Time.now)
      @inscricao.precoTotal += minicurso.preco
      @inscricao.save
    else
      flash[:erro] = true
    end
    @minicurso = Minicurso.all
    @palestras = Palestra.all
    render "index"
  end

  def remover_minicurso
    minicurso_incricao = Minicurso_inscricao.find(params[:id])
    @inscricao = Inscricao.find(params[:inscricao])
    minicurso = Minicurso.find(minicurso_incricao.minicurso)
     #+= 1
    minicurso.save
  minicurso_incricao.destroy
    @Inscricao.precoTotal -= minicurso.preco
    @inscricao.save
    @minicurso = Minicurso.all
    @palestra = Palestra.all
    render "index"
  end


  def adicionar_palestra
    minicurso = Palestra.find(params[:id])
    @inscricao = Inscricao.find(params[:Inscricao])
    if palestra.vagas>=1 && palestra != nil
      palestra.vagas -= 1
      palestra.save
      Palestra_inscricao.create(palestra: palestra, inscricao: @inscricao, data: Time.now)
      @inscricao.precoTotal += palestra.preco
      @inscricao.save
    else
      flash[:erro] = true
    end
    @minicurso = Minicurso.all
    @palestras = Palestra.all
    render "index"
  end



  def remover_palestra
    palestra_inscricaoo = Palestra_inscricao.find(params[:id])
    @inscricao = Inscricao.find(params[:inscricao])
    palestra = Palestra.find(minicurso_incricao.minicurso)
    # += 1
    palestra.save
    Palestra_inscricao.destroy
    @Inscricao.precoTotal -= minicurso.preco
    @inscricao.save
    @minicurso = Minicurso.all
    @palestra = Palestra.all
    render "index"
  end


  def status_servico
    servicos_venda = ServicosVenda.find(params[:id])
    if servicos_venda.status == true
      servicos_venda.status = false
    else
      servicos_venda.status = true
    end
    servicos_venda.save
    @venda = Venda.find(params[:venda])
    @produtos = Produto.all
    @servicos = Servico.all
    render "index"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artigos_helper.rb
module ArtigosHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/contato_helper.rb
module ContatoHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/helpers/member_helper.rb
module MemberHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/minhainscricaos_helper.rb
module MinhainscricaosHelper
end

app/helpers/minicurso_helper.rb
module MinicursoHelper
end

app/helpers/painel_helper.rb
module PainelHelper
end

app/helpers/panelists_helper.rb
module PanelistsHelper
end

app/helpers/parceiros_helper.rb
module ParceirosHelper
end

app/helpers/registres_helper.rb
module RegistresHelper
end

app/views/minhainscricaos/_form.html.erb
<%= form_for(@minhainscricao) do |f| %>
  <% if @minhainscricao.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@minhainscricao.errors.count, "error") %> prohibited this minhainscricao from being saved:</h2>

      <ul>
      <% @minhainscricao.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/minhainscricaos/edit.html.erb
<h1>Editing Minhainscricao</h1>

<%= render 'form' %>

<%= link_to 'Show', @minhainscricao %> |
<%= link_to 'Back', minhainscricaos_path %>

app/views/minhainscricaos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Minhainscricaos</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @minhainscricaos.each do |minhainscricao| %>
      <tr>
        <td><%= link_to 'Show', minhainscricao %></td>
        <td><%= link_to 'Edit', edit_minhainscricao_path(minhainscricao) %></td>
        <td><%= link_to 'Destroy', minhainscricao, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Minhainscricao', new_minhainscricao_path %>

app/views/minhainscricaos/new.html.erb
<h1>New Minhainscricao</h1>

<%= render 'form' %>

<%= link_to 'Back', minhainscricaos_path %>

app/views/minhainscricaos/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_minhainscricao_path(@minhainscricao) %> |
<%= link_to 'Back', minhainscricaos_path %>